version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080

  backend:
    build: .
    ports:
      - "5003:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/testDB?schema=public
    links:
      - db
    depends_on:
      - db
    restart: always
